// <auto-generated />
using System;
using BackendAPICrud.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackendAPICrud.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20250206162520_NewTables")]
    partial class NewTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("BackendAPICrud.Tables.Estudante", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("Estudante");
                });

            modelBuilder.Entity("BackendAPICrud.Tables.Nota", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<double>("Ingles")
                        .HasColumnType("double");

                    b.Property<double>("Matematica")
                        .HasColumnType("double");

                    b.Property<double>("Portugues")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("Notas");
                });

            modelBuilder.Entity("BackendAPICrud.Tables.Registro", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.HasKey("id");

                    b.ToTable("Registros");
                });
#pragma warning restore 612, 618
        }
    }
}
